version: '3'
services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: workshop
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: workshop_one
  web:
    build: .
    links: 
      - postgres
    volumes:
      - ./:/app
    ports:
      - "4567:4567"
    privileged: true
    environment:
      DB_URL: postgresql://workshop:secretpassword@postgres/workshop_one
      POSTGRES_USER: workshop
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: workshop_one
      POSTGRES_PASSWORD: secretpassword